### ISSUE TITLE
/giverole

### ISSUE THREAD

**Issue by josefaidt** [josefaidt/amplify-discord-bots#5]
## Objective

Create command `/giverole` to be used by existing staff and mods to add any role to any user

## Usage

```
/giverole <role> <user>
```

`<role>` and `<user>` should use appropriate Discord slash command argument types

```
/giverole staff @josef
```

## Permissions Needed

Roles that can execute

- Amplify Staff
- Moderator

## Implementation Notes

Command should be registered **without default permissions** to ensure at-everyone/general members cannot add roles to themselves.

**Comment by billygerhard** [comment]
What benefit does this and #2 give beyond just right clicking a name and adding the role?

**Comment by josefaidt** [comment]
Hey @billygerhard :wave: the benefit here would be ease-of-use. With slash commands the arguments will show a list of roles & users that can be filtered with fuzzy matching
